"""Add derivative summary, chunk, graph, and run tables.

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-18 23:53:56.514088
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]
from podex.models.semantic_chunk import PgVectorType

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("summary_key", sa.String(length=120), nullable=False),
        sa.Column("summary_kind", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("source_model", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("short_summary", sa.Text(), nullable=True),
        sa.Column("highlights_json", sa.JSON(), nullable=True),
        sa.Column("citations_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("summary_key", name="uq_media_summaries_summary_key"),
    )
    op.create_index(
        op.f("ix_media_summaries_media_id"),
        "media_summaries",
        ["media_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_summaries_pipeline_version"),
        "media_summaries",
        ["pipeline_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_summaries_prompt_version"),
        "media_summaries",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_summaries_source_model"),
        "media_summaries",
        ["source_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_summaries_source_text_hash"),
        "media_summaries",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_summaries_status"), "media_summaries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_media_summaries_summary_key"),
        "media_summaries",
        ["summary_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_media_summaries_summary_kind"),
        "media_summaries",
        ["summary_kind"],
        unique=False,
    )
    op.create_table(
        "episode_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("summary_key", sa.String(length=120), nullable=False),
        sa.Column("summary_kind", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("source_model", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("short_summary", sa.Text(), nullable=True),
        sa.Column("highlights_json", sa.JSON(), nullable=True),
        sa.Column("citations_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("summary_key", name="uq_episode_summaries_summary_key"),
    )
    op.create_index(
        op.f("ix_episode_summaries_episode_id"),
        "episode_summaries",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_pipeline_version"),
        "episode_summaries",
        ["pipeline_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_prompt_version"),
        "episode_summaries",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_source_model"),
        "episode_summaries",
        ["source_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_source_text_hash"),
        "episode_summaries",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_status"),
        "episode_summaries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_episode_summaries_summary_key"),
        "episode_summaries",
        ["summary_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_episode_summaries_summary_kind"),
        "episode_summaries",
        ["summary_kind"],
        unique=False,
    )
    op.create_table(
        "derivative_generation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_key", sa.String(length=120), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=True),
        sa.Column("episode_summary_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("chunk_pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("summary_prompt_version", sa.String(length=80), nullable=False),
        sa.Column("summary_model", sa.String(length=120), nullable=True),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("semantic_chunks_created", sa.Integer(), nullable=False),
        sa.Column("semantic_chunks_updated", sa.Integer(), nullable=False),
        sa.Column("semantic_chunks_deleted", sa.Integer(), nullable=False),
        sa.Column("semantic_chunks_embedded", sa.Integer(), nullable=False),
        sa.Column("semantic_chunks_failed", sa.Integer(), nullable=False),
        sa.Column("media_summaries_generated", sa.Integer(), nullable=False),
        sa.Column("graph_triples_upserted", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["episode_summary_id"],
            ["episode_summaries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key", name="uq_derivative_generation_runs_run_key"),
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_chunk_pipeline_version"),
        "derivative_generation_runs",
        ["chunk_pipeline_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_episode_id"),
        "derivative_generation_runs",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_episode_summary_id"),
        "derivative_generation_runs",
        ["episode_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_pipeline_version"),
        "derivative_generation_runs",
        ["pipeline_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_run_key"),
        "derivative_generation_runs",
        ["run_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_source_text_hash"),
        "derivative_generation_runs",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_status"),
        "derivative_generation_runs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_summary_model"),
        "derivative_generation_runs",
        ["summary_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_summary_prompt_version"),
        "derivative_generation_runs",
        ["summary_prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derivative_generation_runs_transcript_id"),
        "derivative_generation_runs",
        ["transcript_id"],
        unique=False,
    )
    op.create_table(
        "graph_triples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("triple_key", sa.String(length=96), nullable=False),
        sa.Column("subject_media_id", sa.Integer(), nullable=False),
        sa.Column("predicate", sa.String(length=80), nullable=False),
        sa.Column("object_kind", sa.String(length=32), nullable=False),
        sa.Column("object_media_id", sa.Integer(), nullable=True),
        sa.Column("object_value", sa.String(length=500), nullable=True),
        sa.Column("media_relation_id", sa.Integer(), nullable=True),
        sa.Column("provenance_episode_id", sa.Integer(), nullable=True),
        sa.Column("provenance_mention_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_relation_id"],
            ["media_relations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_media_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_mention_id"],
            ["mentions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("triple_key", name="uq_graph_triples_triple_key"),
    )
    op.create_index(
        op.f("ix_graph_triples_media_relation_id"),
        "graph_triples",
        ["media_relation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_object_kind"),
        "graph_triples",
        ["object_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_object_media_id"),
        "graph_triples",
        ["object_media_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_object_value"),
        "graph_triples",
        ["object_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_predicate"), "graph_triples", ["predicate"], unique=False
    )
    op.create_index(
        op.f("ix_graph_triples_provenance_episode_id"),
        "graph_triples",
        ["provenance_episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_provenance_mention_id"),
        "graph_triples",
        ["provenance_mention_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_source"), "graph_triples", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_graph_triples_subject_media_id"),
        "graph_triples",
        ["subject_media_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_triples_triple_key"),
        "graph_triples",
        ["triple_key"],
        unique=True,
    )
    op.create_table(
        "semantic_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("chunk_key", sa.String(length=180), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Integer(), nullable=True),
        sa.Column("end_seconds", sa.Integer(), nullable=True),
        sa.Column("embedding_status", sa.String(length=32), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.Column(
            "embedding_vector",
            PgVectorType(1536),
            nullable=True,
        ),
        sa.Column("embedding_error", sa.Text(), nullable=True),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_key", name="uq_semantic_chunks_chunk_key"),
    )
    op.create_index(
        op.f("ix_semantic_chunks_chunk_key"),
        "semantic_chunks",
        ["chunk_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_semantic_chunks_embedding_model"),
        "semantic_chunks",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_chunks_embedding_status"),
        "semantic_chunks",
        ["embedding_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_chunks_episode_id"),
        "semantic_chunks",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_chunks_pipeline_version"),
        "semantic_chunks",
        ["pipeline_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_chunks_source_text_hash"),
        "semantic_chunks",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_chunks_transcript_id"),
        "semantic_chunks",
        ["transcript_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_semantic_chunks_transcript_id"), table_name="semantic_chunks"
    )
    op.drop_index(
        op.f("ix_semantic_chunks_source_text_hash"), table_name="semantic_chunks"
    )
    op.drop_index(
        op.f("ix_semantic_chunks_pipeline_version"), table_name="semantic_chunks"
    )
    op.drop_index(op.f("ix_semantic_chunks_episode_id"), table_name="semantic_chunks")
    op.drop_index(
        op.f("ix_semantic_chunks_embedding_status"), table_name="semantic_chunks"
    )
    op.drop_index(
        op.f("ix_semantic_chunks_embedding_model"), table_name="semantic_chunks"
    )
    op.drop_index(op.f("ix_semantic_chunks_chunk_key"), table_name="semantic_chunks")
    op.drop_table("semantic_chunks")
    op.drop_index(op.f("ix_graph_triples_triple_key"), table_name="graph_triples")
    op.drop_index(op.f("ix_graph_triples_subject_media_id"), table_name="graph_triples")
    op.drop_index(op.f("ix_graph_triples_source"), table_name="graph_triples")
    op.drop_index(
        op.f("ix_graph_triples_provenance_mention_id"), table_name="graph_triples"
    )
    op.drop_index(
        op.f("ix_graph_triples_provenance_episode_id"), table_name="graph_triples"
    )
    op.drop_index(op.f("ix_graph_triples_predicate"), table_name="graph_triples")
    op.drop_index(op.f("ix_graph_triples_object_value"), table_name="graph_triples")
    op.drop_index(op.f("ix_graph_triples_object_media_id"), table_name="graph_triples")
    op.drop_index(op.f("ix_graph_triples_object_kind"), table_name="graph_triples")
    op.drop_index(
        op.f("ix_graph_triples_media_relation_id"), table_name="graph_triples"
    )
    op.drop_table("graph_triples")
    op.drop_index(
        op.f("ix_derivative_generation_runs_transcript_id"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_summary_prompt_version"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_summary_model"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_status"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_source_text_hash"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_run_key"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_pipeline_version"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_episode_summary_id"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_episode_id"),
        table_name="derivative_generation_runs",
    )
    op.drop_index(
        op.f("ix_derivative_generation_runs_chunk_pipeline_version"),
        table_name="derivative_generation_runs",
    )
    op.drop_table("derivative_generation_runs")
    op.drop_index(
        op.f("ix_episode_summaries_summary_kind"), table_name="episode_summaries"
    )
    op.drop_index(
        op.f("ix_episode_summaries_summary_key"), table_name="episode_summaries"
    )
    op.drop_index(op.f("ix_episode_summaries_status"), table_name="episode_summaries")
    op.drop_index(
        op.f("ix_episode_summaries_source_text_hash"), table_name="episode_summaries"
    )
    op.drop_index(
        op.f("ix_episode_summaries_source_model"), table_name="episode_summaries"
    )
    op.drop_index(
        op.f("ix_episode_summaries_prompt_version"), table_name="episode_summaries"
    )
    op.drop_index(
        op.f("ix_episode_summaries_pipeline_version"), table_name="episode_summaries"
    )
    op.drop_index(
        op.f("ix_episode_summaries_episode_id"), table_name="episode_summaries"
    )
    op.drop_table("episode_summaries")
    op.drop_index(op.f("ix_media_summaries_summary_kind"), table_name="media_summaries")
    op.drop_index(op.f("ix_media_summaries_summary_key"), table_name="media_summaries")
    op.drop_index(op.f("ix_media_summaries_status"), table_name="media_summaries")
    op.drop_index(
        op.f("ix_media_summaries_source_text_hash"), table_name="media_summaries"
    )
    op.drop_index(op.f("ix_media_summaries_source_model"), table_name="media_summaries")
    op.drop_index(
        op.f("ix_media_summaries_prompt_version"), table_name="media_summaries"
    )
    op.drop_index(
        op.f("ix_media_summaries_pipeline_version"), table_name="media_summaries"
    )
    op.drop_index(op.f("ix_media_summaries_media_id"), table_name="media_summaries")
    op.drop_table("media_summaries")
    # ### end Alembic commands ###
