"""Add transcript retention columns and digest/artifact/policy tables.

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-19 00:22:54.442216
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcript_source_retention_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("podcast_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("hot_days", sa.Integer(), nullable=False),
        sa.Column("warm_days", sa.Integer(), nullable=False),
        sa.Column("min_purge_confidence", sa.Float(), nullable=False),
        sa.Column("source_retention_opt_out", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["podcast_id"],
            ["podcasts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "podcast_id",
            "source_key",
            name="uq_transcript_source_retention_policies_source",
        ),
    )
    op.create_index(
        op.f("ix_transcript_source_retention_policies_podcast_id"),
        "transcript_source_retention_policies",
        ["podcast_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_source_retention_policies_source_key"),
        "transcript_source_retention_policies",
        ["source_key"],
        unique=False,
    )
    op.create_table(
        "transcript_digests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("digest_key", sa.String(length=160), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("sampling_strata_json", sa.JSON(), nullable=True),
        sa.Column("extraction_versions_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest_key", name="uq_transcript_digests_digest_key"),
    )
    op.create_index(
        op.f("ix_transcript_digests_digest_key"),
        "transcript_digests",
        ["digest_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transcript_digests_episode_id"),
        "transcript_digests",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_digests_source_text_hash"),
        "transcript_digests",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_digests_transcript_id"),
        "transcript_digests",
        ["transcript_id"],
        unique=False,
    )
    op.create_table(
        "transcript_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("reacquired_from_digest_id", sa.Integer(), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("encryption_key_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("provenance_json", sa.JSON(), nullable=True),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reacquired_from_digest_id"],
            ["transcript_digests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_artifacts_episode_id"),
        "transcript_artifacts",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_artifacts_reacquired_from_digest_id"),
        "transcript_artifacts",
        ["reacquired_from_digest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_artifacts_source_text_hash"),
        "transcript_artifacts",
        ["source_text_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_artifacts_storage_key"),
        "transcript_artifacts",
        ["storage_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transcript_artifacts_transcript_id"),
        "transcript_artifacts",
        ["transcript_id"],
        unique=False,
    )
    op.add_column(
        "transcripts", sa.Column("retention_tier", sa.String(length=32), nullable=False)
    )
    op.add_column(
        "transcripts",
        sa.Column("retention_policy_version", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "transcripts",
        sa.Column("retention_evaluated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "transcripts",
        sa.Column("retention_exempt_sample", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "transcripts", sa.Column("retention_sample_rate", sa.Float(), nullable=True)
    )
    op.add_column(
        "transcripts", sa.Column("retention_sample_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "transcripts",
        sa.Column("retention_sample_strata_json", sa.JSON(), nullable=True),
    )
    op.add_column(
        "transcripts",
        sa.Column("source_retention_opt_out", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "transcripts", sa.Column("retention_blockers_json", sa.JSON(), nullable=True)
    )
    op.add_column("transcripts", sa.Column("digest_text", sa.Text(), nullable=True))
    op.add_column(
        "transcripts",
        sa.Column("digest_created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "transcripts",
        sa.Column("purge_eligible_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "transcripts", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_transcripts_retention_tier"),
        "transcripts",
        ["retention_tier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcripts_retention_tier"), table_name="transcripts")
    op.drop_column("transcripts", "purged_at")
    op.drop_column("transcripts", "purge_eligible_at")
    op.drop_column("transcripts", "digest_created_at")
    op.drop_column("transcripts", "digest_text")
    op.drop_column("transcripts", "retention_blockers_json")
    op.drop_column("transcripts", "source_retention_opt_out")
    op.drop_column("transcripts", "retention_sample_strata_json")
    op.drop_column("transcripts", "retention_sample_score")
    op.drop_column("transcripts", "retention_sample_rate")
    op.drop_column("transcripts", "retention_exempt_sample")
    op.drop_column("transcripts", "retention_evaluated_at")
    op.drop_column("transcripts", "retention_policy_version")
    op.drop_column("transcripts", "retention_tier")
    op.drop_index(
        op.f("ix_transcript_artifacts_transcript_id"), table_name="transcript_artifacts"
    )
    op.drop_index(
        op.f("ix_transcript_artifacts_storage_key"), table_name="transcript_artifacts"
    )
    op.drop_index(
        op.f("ix_transcript_artifacts_source_text_hash"),
        table_name="transcript_artifacts",
    )
    op.drop_index(
        op.f("ix_transcript_artifacts_reacquired_from_digest_id"),
        table_name="transcript_artifacts",
    )
    op.drop_index(
        op.f("ix_transcript_artifacts_episode_id"), table_name="transcript_artifacts"
    )
    op.drop_table("transcript_artifacts")
    op.drop_index(
        op.f("ix_transcript_digests_transcript_id"), table_name="transcript_digests"
    )
    op.drop_index(
        op.f("ix_transcript_digests_source_text_hash"), table_name="transcript_digests"
    )
    op.drop_index(
        op.f("ix_transcript_digests_episode_id"), table_name="transcript_digests"
    )
    op.drop_index(
        op.f("ix_transcript_digests_digest_key"), table_name="transcript_digests"
    )
    op.drop_table("transcript_digests")
    op.drop_index(
        op.f("ix_transcript_source_retention_policies_source_key"),
        table_name="transcript_source_retention_policies",
    )
    op.drop_index(
        op.f("ix_transcript_source_retention_policies_podcast_id"),
        table_name="transcript_source_retention_policies",
    )
    op.drop_table("transcript_source_retention_policies")
    # ### end Alembic commands ###
