/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Account Session
         * @description Revoke the current account session and expire its browser cookie.
         */
        post: operations["logout_account_session_api_v2_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Auth Magic Link
         * @description Request delivery of a short-lived, single-use email sign-in link.
         */
        post: operations["request_auth_magic_link_api_v2_auth_magic_link_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Auth Magic Link
         * @description Verify a one-time link token and begin an authenticated session.
         */
        post: operations["verify_auth_magic_link_api_v2_auth_magic_link_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Episodes
         * @description List episodes, optionally filtered by podcast, paginated.
         */
        get: operations["list_episodes_api_v2_episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episode
         * @description Return a single episode by id.
         */
        get: operations["get_episode_api_v2_episodes__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/episodes/{episode_id}/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Episode Mentions
         * @description List media mentions within an episode, ordered by timestamp, paginated.
         */
        get: operations["list_episode_mentions_api_v2_episodes__episode_id__mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Account
         * @description Return the account represented by the current browser session.
         */
        get: operations["get_current_account_api_v2_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Account Alert Rules
         * @description List alert rules belonging to the authenticated account.
         */
        get: operations["list_account_alert_rules_api_v2_me_alerts_get"];
        put?: never;
        /**
         * Create Account Alert Rule
         * @description Create an alert rule for a saved media or followed podcast resource.
         */
        post: operations["create_account_alert_rule_api_v2_me_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/alerts/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Account Alert Rules
         * @description Evaluate alert rules and generate events for new published activity.
         */
        post: operations["evaluate_account_alert_rules_api_v2_me_alerts_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/alerts/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account Alert Rule
         * @description Remove an alert rule belonging to the authenticated account.
         */
        delete: operations["delete_account_alert_rule_api_v2_me_alerts__rule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Account Alert Rule
         * @description Pause or resume an account alert rule.
         */
        patch: operations["update_account_alert_rule_api_v2_me_alerts__rule_id__patch"];
        trace?: never;
    };
    "/api/v2/me/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Current Account Digests
         * @description List delivered notification digests for the current account.
         */
        get: operations["list_current_account_digests_api_v2_me_digests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/digests/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Current Account Digest
         * @description Evaluate alert rules and deliver pending activity by email.
         */
        post: operations["send_current_account_digest_api_v2_me_digests_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Account Followed Podcasts
         * @description List followed public podcast sources for the current account.
         */
        get: operations["list_account_followed_podcasts_api_v2_me_follows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/follows/{podcast_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Account Followed Podcast
         * @description Idempotently follow a public podcast source.
         */
        put: operations["put_account_followed_podcast_api_v2_me_follows__podcast_id__put"];
        post?: never;
        /**
         * Delete Account Followed Podcast
         * @description Remove a public podcast source from the current account's follows.
         */
        delete: operations["delete_account_followed_podcast_api_v2_me_follows__podcast_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Account Preferences
         * @description Return persisted notification preferences for the signed-in account.
         */
        get: operations["get_current_account_preferences_api_v2_me_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current Account Preferences
         * @description Update notification preferences for the signed-in account.
         */
        patch: operations["update_current_account_preferences_api_v2_me_preferences_patch"];
        trace?: never;
    };
    "/api/v2/me/saves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Account Saved Media
         * @description List saved public catalog media for the current account.
         */
        get: operations["list_account_saved_media_api_v2_me_saves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/saves/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Account Saved Media
         * @description Idempotently save a public catalog media record.
         */
        put: operations["put_account_saved_media_api_v2_me_saves__media_id__put"];
        post?: never;
        /**
         * Delete Account Saved Media
         * @description Remove a public catalog media record from the current account's saves.
         */
        delete: operations["delete_account_saved_media_api_v2_me_saves__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Account Subscription
         * @description Return hosted plan entitlement and current monthly usage.
         */
        get: operations["get_current_account_subscription_api_v2_me_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/me/subscription/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin Current Account Checkout
         * @description Start provider-hosted paid-tier checkout once launch gates are enabled.
         */
        post: operations["begin_current_account_checkout_api_v2_me_subscription_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Media
         * @description List media items, optionally filtered by type, paginated.
         */
        get: operations["list_media_api_v2_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media
         * @description Return a single media item by id.
         */
        get: operations["get_media_api_v2_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/media/{media_id}/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Media Mentions
         * @description List episode mentions of a media item, paginated.
         */
        get: operations["list_media_mentions_api_v2_media__media_id__mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Operational Alerts
         * @description Return configured operational threshold breaches.
         */
        get: operations["get_ops_operational_alerts_api_v2_ops_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Audit Log
         * @description List immutable audit records, newest first.
         */
        get: operations["get_ops_audit_log_api_v2_ops_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Metrics
         * @description Return operational dashboard metrics.
         */
        get: operations["get_ops_metrics_api_v2_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Pipelines
         * @description Return recent ingestion run activity.
         */
        get: operations["get_ops_pipelines_api_v2_ops_pipelines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/podcasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ops Podcasts Endpoint
         * @description List managed podcasts with filters and count sorting.
         */
        get: operations["list_ops_podcasts_endpoint_api_v2_ops_podcasts_get"];
        put?: never;
        /**
         * Create Ops Podcast Endpoint
         * @description Create a managed podcast and record the action.
         */
        post: operations["create_ops_podcast_endpoint_api_v2_ops_podcasts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/podcasts/{podcast_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ops Podcast Endpoint
         * @description Return one managed podcast summary.
         */
        get: operations["get_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Ops Podcast Endpoint
         * @description Partially update a managed podcast and record the action.
         */
        patch: operations["update_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__patch"];
        trace?: never;
    };
    "/api/v2/ops/podcasts/{podcast_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Ops Podcast Endpoint
         * @description Pause a managed podcast and record the action.
         */
        post: operations["archive_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ops Retention
         * @description List recent transcript assets for retention review.
         */
        get: operations["list_ops_retention_api_v2_ops_retention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/retention/{transcript_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Ops Retention
         * @description Persist a retention evaluation and record the action.
         */
        post: operations["apply_ops_retention_api_v2_ops_retention__transcript_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/retention/{transcript_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Ops Retention
         * @description Dry-run the retention policy for one transcript.
         */
        get: operations["preview_ops_retention_api_v2_ops_retention__transcript_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ops/retention/{transcript_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Ops Transcript Endpoint
         * @description Purge an eligible transcript and record the action.
         */
        post: operations["purge_ops_transcript_endpoint_api_v2_ops_retention__transcript_id__purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/podcasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Podcasts
         * @description List podcast sources ordered by name, paginated by ``limit``/``offset``.
         */
        get: operations["list_podcasts_api_v2_podcasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/podcasts/{podcast_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Podcast
         * @description Return a single podcast source by id.
         */
        get: operations["get_podcast_api_v2_podcasts__podcast_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog Stats
         * @description Return catalog-wide counts and a small top-media-types breakdown.
         *
         *     Responses are cached in-process for
         *     ``PODEX_STATS_CACHE_TTL_SECONDS`` seconds (configurable via
         *     :class:`~podex.config.Settings`); set the TTL to ``0`` to bypass the
         *     cache entirely.
         */
        get: operations["get_catalog_stats_api_v2_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Status
         * @description Report that the v2 API surface is reachable.
         */
        get: operations["read_status_api_v2_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountUserRead
         * @description Public representation of the signed-in account.
         */
        AccountUserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Last Signed In At */
            last_signed_in_at: string | null;
        };
        /**
         * AlertEvaluationRead
         * @description Result of evaluating the account's alert rules.
         */
        AlertEvaluationRead: {
            /** Generated */
            generated: number;
            /** Items */
            items: components["schemas"]["AlertEventRead"][];
        };
        /**
         * AlertEventRead
         * @description A generated alert event and its owning rule.
         */
        AlertEventRead: {
            /** Observed Count */
            observed_count: number;
            /** Previous Count */
            previous_count: number;
            rule: components["schemas"]["AlertRuleRead"];
        };
        /**
         * AlertRuleCreateRequest
         * @description Create an alert rule over a linked public resource.
         */
        AlertRuleCreateRequest: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "new_mention" | "new_episode";
            /** Target Id */
            target_id: number;
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "media" | "podcast";
        };
        /**
         * AlertRuleDeleteResponse
         * @description Result of removing an alert rule.
         */
        AlertRuleDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * AlertRuleListRead
         * @description Alert rule collection for the current account.
         */
        AlertRuleListRead: {
            /** Items */
            items: components["schemas"]["AlertRuleRead"][];
            /** Total */
            total: number;
        };
        /**
         * AlertRuleRead
         * @description Public representation of one account alert rule.
         */
        AlertRuleRead: {
            /** Baseline Count */
            baseline_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Last Evaluated At */
            last_evaluated_at: string | null;
            /** Target Id */
            target_id: number;
            /** Target Type */
            target_type: string;
        };
        /**
         * AlertRuleUpdateRequest
         * @description Pause or resume an alert rule.
         */
        AlertRuleUpdateRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * AuthLogoutResponse
         * @description Result of revoking the current browser session.
         */
        AuthLogoutResponse: {
            /** Signed Out */
            signed_out: boolean;
        };
        /**
         * AuthMagicLinkRequest
         * @description Request delivery of a one-time email sign-in link.
         */
        AuthMagicLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Redirect Path */
            redirect_path?: string | null;
        };
        /**
         * AuthMagicLinkRequestResponse
         * @description Acknowledgement that a sign-in link was accepted for delivery.
         */
        AuthMagicLinkRequestResponse: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
        };
        /**
         * AuthMagicLinkVerifyRequest
         * @description Redeem a one-time sign-in token.
         */
        AuthMagicLinkVerifyRequest: {
            /** Token */
            token: string;
        };
        /**
         * AuthSessionRead
         * @description Authenticated session summary returned after verification.
         */
        AuthSessionRead: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["AccountUserRead"];
        };
        /**
         * CatalogStats
         * @description Top-level catalog counters plus a small top-list breakdown.
         *
         *     Attributes:
         *         podcasts: Total podcast sources in the catalog.
         *         episodes: Total episodes across all sources.
         *         media: Total canonical media items in the catalog. Counts every
         *             ``Media`` row, not just those referenced by a mention.
         *         mentions: Total episode<->media mention links.
         *         top_media_types: Up to five media types ordered by descending count,
         *             with ties broken alphabetically by type name for stability.
         */
        CatalogStats: {
            /** Episodes */
            episodes: number;
            /**
             * Media
             * @description Total canonical media items in the catalog (every Media row).
             */
            media: number;
            /** Mentions */
            mentions: number;
            /** Podcasts */
            podcasts: number;
            /**
             * Top Media Types
             * @description Up to five media types ordered by descending count; ties broken alphabetically by type name.
             */
            top_media_types: components["schemas"]["MediaTypeCount"][];
        };
        /**
         * DigestListRead
         * @description Delivered digest collection for the current account.
         */
        DigestListRead: {
            /** Items */
            items: components["schemas"]["DigestRead"][];
            /** Total */
            total: number;
        };
        /**
         * DigestRead
         * @description Public representation of a delivered notification digest.
         */
        DigestRead: {
            /** Body Text */
            body_text: string;
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered At */
            delivered_at: string | null;
            /** Event Count */
            event_count: number;
            /** Id */
            id: number;
            /** Subject */
            subject: string;
        };
        /**
         * DigestSendResponse
         * @description Result of an on-demand digest delivery attempt.
         */
        DigestSendResponse: {
            /** Delivered */
            delivered: boolean;
            digest?: components["schemas"]["DigestRead"] | null;
        };
        /**
         * EpisodeRead
         * @description Public representation of a podcast episode.
         */
        EpisodeRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Episode Number */
            episode_number: number | null;
            /** Id */
            id: number;
            /** Podcast Id */
            podcast_id: number;
            /**
             * Podcast Public Id
             * @description The opaque public identifier of the owning podcast.
             */
            readonly podcast_public_id: string;
            /**
             * Public Id
             * @description The opaque, prefixed public identifier for this episode.
             */
            readonly public_id: string;
            /** Published At */
            published_at: string | null;
            /** Title */
            title: string;
        };
        /**
         * FollowedPodcastDeleteResponse
         * @description Result of removing a followed podcast.
         */
        FollowedPodcastDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * FollowedPodcastListRead
         * @description Followed podcast collection for the current account.
         */
        FollowedPodcastListRead: {
            /** Items */
            items: components["schemas"]["FollowedPodcastRead"][];
            /** Total */
            total: number;
        };
        /**
         * FollowedPodcastRead
         * @description A followed public podcast source and when it was followed.
         */
        FollowedPodcastRead: {
            /**
             * Followed At
             * Format: date-time
             */
            followed_at: string;
            podcast: components["schemas"]["PodcastRead"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MediaRead
         * @description Public representation of a canonical media item.
         */
        MediaRead: {
            /** Author */
            author: string | null;
            /** Cover Url */
            cover_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /**
             * Public Id
             * @description The opaque, prefixed public identifier for this media item.
             */
            readonly public_id: string;
            /** Title */
            title: string;
            type: components["schemas"]["MediaType"];
            /** Year */
            year: number | null;
        };
        /**
         * MediaType
         * @description The kind of media a catalog item represents.
         * @enum {string}
         */
        MediaType: "book" | "movie" | "documentary" | "tv_show" | "study" | "podcast" | "article" | "person" | "place";
        /**
         * MediaTypeCount
         * @description One row of the ``top_media_types`` breakdown.
         */
        MediaTypeCount: {
            /**
             * Count
             * @description Number of media rows of this type.
             */
            count: number;
            /**
             * Media Type
             * @description MediaType value (e.g. ``book``, ``movie``).
             */
            media_type: string;
        };
        /**
         * MentionRead
         * @description Public representation of a media mention within an episode.
         */
        MentionRead: {
            /** Confidence */
            confidence: number | null;
            /** Context */
            context: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Episode Id */
            episode_id: number;
            /**
             * Episode Public Id
             * @description The opaque public identifier of the referenced episode.
             */
            readonly episode_public_id: string;
            /** Id */
            id: number;
            /** Media Id */
            media_id: number;
            /**
             * Media Public Id
             * @description The opaque public identifier of the referenced media item.
             */
            readonly media_public_id: string;
            /**
             * Public Id
             * @description The opaque, prefixed public identifier for this mention.
             */
            readonly public_id: string;
            /** Timestamp Seconds */
            timestamp_seconds: number | null;
        };
        /**
         * OpsAlertDeliveryRead
         * @description Generated and delivered account notification health.
         */
        OpsAlertDeliveryRead: {
            /** Delivered Digests Last 24H */
            delivered_digests_last_24h: number;
            /** Delivered Events Last 24H */
            delivered_events_last_24h: number;
            /** Generated Events Last 24H */
            generated_events_last_24h: number;
            /** Pending Events */
            pending_events: number;
        };
        /**
         * OpsAuditLogEntryRead
         * @description One immutable audit record.
         */
        OpsAuditLogEntryRead: {
            /** Action */
            action: string;
            /** Actor Name */
            actor_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            } | null;
            /** Resource Id */
            resource_id: number | null;
            /** Resource Identifier */
            resource_identifier: string | null;
            /** Resource Type */
            resource_type: string;
            /** Summary */
            summary: string;
        };
        /**
         * OpsAuditLogListRead
         * @description Paginated audit log payload.
         */
        OpsAuditLogListRead: {
            /** Items */
            items: components["schemas"]["OpsAuditLogEntryRead"][];
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
        };
        /**
         * OpsIngestionRunRead
         * @description Ingestion run summary for pipeline views.
         */
        OpsIngestionRunRead: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Error Summary */
            error_summary: string | null;
            /** Id */
            id: number;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /**
         * OpsMetricsRead
         * @description Combined operational metrics for the ops dashboard.
         */
        OpsMetricsRead: {
            alerts: components["schemas"]["OpsAlertDeliveryRead"];
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            review: components["schemas"]["OpsReviewThroughputRead"];
        };
        /**
         * OpsOperationalAlertListRead
         * @description Threshold breaches measured from operational metrics.
         */
        OpsOperationalAlertListRead: {
            /** Alerts */
            alerts: components["schemas"]["OpsOperationalAlertRead"][];
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
        };
        /**
         * OpsOperationalAlertRead
         * @description One actionable operator-facing health alert.
         */
        OpsOperationalAlertRead: {
            /** Current Value */
            current_value: number;
            /** Key */
            key: string;
            /** Message */
            message: string;
            /** Playbook Slug */
            playbook_slug: string;
            /** Severity */
            severity: string;
            /** Threshold */
            threshold: number;
            /** Title */
            title: string;
        };
        /**
         * OpsPipelineActivityRead
         * @description Recent pipeline activity.
         */
        OpsPipelineActivityRead: {
            /** Runs */
            runs: components["schemas"]["OpsIngestionRunRead"][];
        };
        /**
         * OpsPodcastCreateRequest
         * @description Create a managed podcast.
         */
        OpsPodcastCreateRequest: {
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /** Discovery Source */
            discovery_source?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** @default {} */
            sources: components["schemas"]["OpsPodcastSourcesInput"];
            /** @default watchlist */
            status: components["schemas"]["PodcastStatus"];
        };
        /**
         * OpsPodcastListRead
         * @description Paginated podcast management payload.
         */
        OpsPodcastListRead: {
            /** Items */
            items: components["schemas"]["OpsPodcastRead"][];
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
        };
        /**
         * OpsPodcastRead
         * @description Podcast summary for ops catalog management views.
         */
        OpsPodcastRead: {
            /** Cover Url */
            cover_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Discovery Source */
            discovery_source: string | null;
            /** Episode Count */
            episode_count: number;
            /** Id */
            id: number;
            /** Mention Count */
            mention_count: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            sources: components["schemas"]["OpsPodcastSourcesRead"];
            status: components["schemas"]["PodcastStatus"];
        };
        /**
         * OpsPodcastSourcesInput
         * @description Source identifiers accepted on podcast mutations.
         */
        OpsPodcastSourcesInput: {
            /** Apple Id */
            apple_id?: string | null;
            /** Podscripts Slug */
            podscripts_slug?: string | null;
            /** Rss Url */
            rss_url?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Youtube Channel Id */
            youtube_channel_id?: string | null;
        };
        /**
         * OpsPodcastSourcesRead
         * @description Source identifiers associated with a managed podcast.
         */
        OpsPodcastSourcesRead: {
            /** Apple Id */
            apple_id: string | null;
            /** Podscripts Slug */
            podscripts_slug: string | null;
            /** Rss Url */
            rss_url: string | null;
            /** Spotify Id */
            spotify_id: string | null;
            /** Youtube Channel Id */
            youtube_channel_id: string | null;
        };
        /**
         * OpsPodcastUpdateRequest
         * @description Partially update a managed podcast; only provided fields change.
         */
        OpsPodcastUpdateRequest: {
            /** Cover Url */
            cover_url?: string | null;
            /** Description */
            description?: string | null;
            /** Discovery Source */
            discovery_source?: string | null;
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
            sources?: components["schemas"]["OpsPodcastSourcesInput"] | null;
            status?: components["schemas"]["PodcastStatus"] | null;
        };
        /**
         * OpsRetentionDecisionRead
         * @description Lifecycle decision produced by a retention evaluation.
         */
        OpsRetentionDecisionRead: {
            /** Age Days */
            age_days: number;
            /** Purge Blockers */
            purge_blockers: string[];
            /** Purge Eligible */
            purge_eligible: boolean;
            /** Retention Suppressed */
            retention_suppressed: boolean;
            /** Tier */
            tier: string;
        };
        /**
         * OpsRetentionPreviewRead
         * @description Dry-run lifecycle result plus derivative safety gate.
         */
        OpsRetentionPreviewRead: {
            decision: components["schemas"]["OpsRetentionDecisionRead"];
            /** Derivative Coverage Ready */
            derivative_coverage_ready: boolean;
            /** Extraction Confidence */
            extraction_confidence: number | null;
            /** Missing Query Classes */
            missing_query_classes: string[];
            transcript: components["schemas"]["OpsTranscriptRetentionRead"];
        };
        /**
         * OpsReviewThroughputRead
         * @description Review decision activity and outstanding pressure.
         */
        OpsReviewThroughputRead: {
            /** Decisions Last 24H */
            decisions_last_24h: number;
            /** Median Decision Minutes Last 24H */
            median_decision_minutes_last_24h: number | null;
            /** Pending Items */
            pending_items: number;
        };
        /**
         * OpsTranscriptPurgeRead
         * @description Result of an operator-approved transcript purge.
         */
        OpsTranscriptPurgeRead: {
            /** Digest Id */
            digest_id: number;
            transcript: components["schemas"]["OpsTranscriptRetentionRead"];
        };
        /**
         * OpsTranscriptRetentionRead
         * @description Operator-facing state for one raw transcript asset.
         */
        OpsTranscriptRetentionRead: {
            /** Digest Id */
            digest_id: number | null;
            /** Episode Id */
            episode_id: number;
            /** Episode Title */
            episode_title: string;
            /** Fetched At */
            fetched_at: string | null;
            /** Has Raw Payload */
            has_raw_payload: boolean;
            /** Has Stored Artifact */
            has_stored_artifact: boolean;
            /** Id */
            id: number;
            /** Podcast Name */
            podcast_name: string;
            /** Policy Version */
            policy_version: string | null;
            /** Provider */
            provider: string;
            /** Purge Eligible At */
            purge_eligible_at: string | null;
            /** Purged At */
            purged_at: string | null;
            /** Retention Exempt Sample */
            retention_exempt_sample: boolean;
            /** Source Retention Opt Out */
            source_retention_opt_out: boolean;
            /** Tier */
            tier: string;
        };
        /** Page[EpisodeRead] */
        Page_EpisodeRead_: {
            /** Items */
            items: components["schemas"]["EpisodeRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[MediaRead] */
        Page_MediaRead_: {
            /** Items */
            items: components["schemas"]["MediaRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[MentionRead] */
        Page_MentionRead_: {
            /** Items */
            items: components["schemas"]["MentionRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[PodcastRead] */
        Page_PodcastRead_: {
            /** Items */
            items: components["schemas"]["PodcastRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PodcastRead
         * @description Public representation of a podcast source.
         */
        PodcastRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Public Id
             * @description The opaque, prefixed public identifier for this podcast.
             */
            readonly public_id: string;
            /** Slug */
            slug: string;
        };
        /**
         * PodcastSourceType
         * @description Supported source filters for ops podcast management views.
         * @enum {string}
         */
        PodcastSourceType: "rss" | "spotify" | "apple" | "youtube" | "podscripts";
        /**
         * PodcastStatus
         * @description Status of a podcast in the processing workflow.
         * @enum {string}
         */
        PodcastStatus: "watchlist" | "active" | "paused";
        /**
         * PreferenceRead
         * @description Notification preferences for the current account.
         */
        PreferenceRead: {
            /** Digest Enabled */
            digest_enabled: boolean;
            /** Digest Frequency */
            digest_frequency: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PreferenceUpdateRequest
         * @description Update notification preferences.
         */
        PreferenceUpdateRequest: {
            /** Digest Enabled */
            digest_enabled: boolean;
            /**
             * Digest Frequency
             * @enum {string}
             */
            digest_frequency: "immediate" | "daily" | "weekly";
        };
        /**
         * QuotaRead
         * @description One monthly feature quota and its current consumption.
         */
        QuotaRead: {
            /** Feature */
            feature: string;
            /** Limit */
            limit: number;
            /** Period */
            period: string;
            /** Remaining */
            remaining: number;
            /** Used */
            used: number;
        };
        /**
         * SavedMediaDeleteResponse
         * @description Result of removing a saved media record.
         */
        SavedMediaDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * SavedMediaListRead
         * @description Saved media collection for the current account.
         */
        SavedMediaListRead: {
            /** Items */
            items: components["schemas"]["SavedMediaRead"][];
            /** Total */
            total: number;
        };
        /**
         * SavedMediaRead
         * @description A saved public media record and when it was saved.
         */
        SavedMediaRead: {
            media: components["schemas"]["MediaRead"];
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /**
         * SubscriptionCheckoutRead
         * @description External provider-hosted checkout destination.
         */
        SubscriptionCheckoutRead: {
            /** Checkout Url */
            checkout_url: string;
            /** Provider */
            provider: string;
        };
        /**
         * SubscriptionRead
         * @description Hosted plan entitlement and current monthly usage.
         */
        SubscriptionRead: {
            /** Current Period Ends At */
            current_period_ends_at: string | null;
            /** Paid Features Enforced */
            paid_features_enforced: boolean;
            /** Quotas */
            quotas: components["schemas"]["QuotaRead"][];
            /** Status */
            status: string;
            /** Tier */
            tier: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_account_session_api_v2_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLogoutResponse"];
                };
            };
        };
    };
    request_auth_magic_link_api_v2_auth_magic_link_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthMagicLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMagicLinkRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_auth_magic_link_api_v2_auth_magic_link_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthMagicLinkVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_api_v2_episodes_get: {
        parameters: {
            query?: {
                podcast_id?: number | null;
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Number of items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EpisodeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_episode_api_v2_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episode_mentions_api_v2_episodes__episode_id__mentions_get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Number of items to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MentionRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_account_api_v2_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountUserRead"];
                };
            };
        };
    };
    list_account_alert_rules_api_v2_me_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleListRead"];
                };
            };
        };
    };
    create_account_alert_rule_api_v2_me_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_account_alert_rules_api_v2_me_alerts_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertEvaluationRead"];
                };
            };
        };
    };
    delete_account_alert_rule_api_v2_me_alerts__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_alert_rule_api_v2_me_alerts__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_current_account_digests_api_v2_me_digests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestListRead"];
                };
            };
        };
    };
    send_current_account_digest_api_v2_me_digests_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestSendResponse"];
                };
            };
        };
    };
    list_account_followed_podcasts_api_v2_me_follows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowedPodcastListRead"];
                };
            };
        };
    };
    put_account_followed_podcast_api_v2_me_follows__podcast_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowedPodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_followed_podcast_api_v2_me_follows__podcast_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowedPodcastDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_account_preferences_api_v2_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceRead"];
                };
            };
        };
    };
    update_current_account_preferences_api_v2_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_account_saved_media_api_v2_me_saves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMediaListRead"];
                };
            };
        };
    };
    put_account_saved_media_api_v2_me_saves__media_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMediaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_saved_media_api_v2_me_saves__media_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMediaDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_account_subscription_api_v2_me_subscription_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRead"];
                };
            };
        };
    };
    begin_current_account_checkout_api_v2_me_subscription_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionCheckoutRead"];
                };
            };
        };
    };
    list_media_api_v2_media_get: {
        parameters: {
            query?: {
                media_type?: components["schemas"]["MediaType"] | null;
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Number of items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MediaRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_api_v2_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_mentions_api_v2_media__media_id__mentions_get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Number of items to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MentionRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_operational_alerts_api_v2_ops_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOperationalAlertListRead"];
                };
            };
        };
    };
    get_ops_audit_log_api_v2_ops_audit_log_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                resource_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsAuditLogListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_metrics_api_v2_ops_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsMetricsRead"];
                };
            };
        };
    };
    get_ops_pipelines_api_v2_ops_pipelines_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPipelineActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_podcasts_endpoint_api_v2_ops_podcasts_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                status?: components["schemas"]["PodcastStatus"] | null;
                source?: components["schemas"]["PodcastSourceType"] | null;
                sort?: "created_at" | "name" | "episode_count" | "mention_count";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPodcastListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ops_podcast_endpoint_api_v2_ops_podcasts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsPodcastCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsPodcastUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_ops_podcast_endpoint_api_v2_ops_podcasts__podcast_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsPodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_retention_api_v2_ops_retention_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsTranscriptRetentionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_ops_retention_api_v2_ops_retention__transcript_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsRetentionPreviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_ops_retention_api_v2_ops_retention__transcript_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsRetentionPreviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_ops_transcript_endpoint_api_v2_ops_retention__transcript_id__purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcript_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsTranscriptPurgeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_podcasts_api_v2_podcasts_get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
                /** @description Number of items to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PodcastRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_podcast_api_v2_podcasts__podcast_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                podcast_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PodcastRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_stats_api_v2_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStats"];
                };
            };
        };
    };
    read_status_api_v2_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
