---
name: Security - OpenSSF Scorecard Analysis
# Weekly OpenSSF Scorecard security analysis.

"on":
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecards:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-scorecards.yml@698a8e882384872913a9b5cf31a38eb240efb549  # v0.57.1
    with:
      job-name: "🛡️ Scorecard Analysis"
      egress-policy: block
      allowed-endpoints: >
        github.com:443
        api.github.com:443
        codeload.github.com:443
        objects.githubusercontent.com:443
        raw.githubusercontent.com:443
        pipelines.actions.githubusercontent.com:443
        gcr.io:443
        api.osv.dev:443
        api.scorecard.dev:443
        api.securityscorecards.dev:443
        agent.api.stepsecurity.io:443
        api.deps.dev:443
        api.osv.dev:443
        api.scorecard.dev:443
        fulcio.sigstore.dev:443
        rekor.sigstore.dev:443
        sigstore.dev:443
        tuf-repo-cdn.sigstore.dev:443
        release-assets.githubusercontent.com:443
        oss-fuzz-build-logs.storage.googleapis.com:443
        ossf.github.io:443
        www.bestpractices.dev:443
    permissions:
      contents: read
      security-events: write
      id-token: write
