---
name: Quality Check - Action Pinning Validation

"on":
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  workflow_dispatch:

permissions: {}

concurrency:
  group: validate-action-pinning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-validate-action-pinning.yml@8a6b1f553f1a0400a70db8910094073ce803cc4d  # v0.69.5
    with:
      job-name: '📌 Validate Action Pinning'
      tooling-ref: '8a6b1f553f1a0400a70db8910094073ce803cc4d' # v0.69.5
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
